# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
